version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html/Todo
    volumes:
      - .:/var/www/html/Todo
    environment:
      - APP_ENV=local
    depends_on:
      - db
    networks:
      - laravel

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/Todo
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
