services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html/Todo
    volumes:
      - .:/var/www/html/Todo
      - app_socket:/run/php/php8.1-fpm.sock  # Volume to share socket file
    environment:
      - APP_ENV=local
    networks:
      - bridge

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/Todo
      - app_socket:/run/php/php8.1-fpm.sock  # Volume to share socket file
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
    depends_on:
      - app
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  app_socket:  # Define shared volume for the socket



