version: '28.0.1'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html/Todo
    volumes:
      - .:/var/www/html/Todo
    environment:
      - APP_ENV=local
    # depends_on:
    #   - db
    networks:
      - laravel

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/Todo
    depends_on:
      - app
    networks:
      - laravel

  # db:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   networks:
  #     - laravel

networks:
  laravel:

# volumes:
#   dbdata:
